<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SistemOtoritasSeed extends Seeder
{
    public function run()
    {
        $data = [
            [
                'auth_permissions_id'       => 1,
                'judul'                     => 'Pengaturan',
                'icon'                      => 'mdi mdi-settings',
                'icon_color'                => '#ffab00',
                'jenis'                     => 'Menu',
                'parent_name'               => '',
                'urut'                      => 1,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 2,
                'judul'                     => 'Desain Menu',
                'icon'                      => 'mdi mdi-menu',
                'icon_color'                => 'rgb(182, 215, 168)',
                'jenis'                     => 'Menu',
                'parent_name'               => 'pengaturan',
                'urut'                      => 0,
                'url'                       => 'pengaturan',
                'is_page'                   => 1,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 3,
                'judul'                     => 'Lihat Desain Menu',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'desain_menu',
                'urut'                      => 0,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 4,
                'judul'                     => 'Tambah Menu',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'desain_menu',
                'urut'                      => 1,
                'url'                       => '',
                'is_page'                   => 1,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 5,
                'judul'                     => 'Edit Menu',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'desain_menu',
                'urut'                      => 2,
                'url'                       => '',
                'is_page'                   => 1,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 6,
                'judul'                     => 'Hapus Menu',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'desain_menu',
                'urut'                      => 3,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 7,
                'judul'                     => 'Manajemen User',
                'icon'                      => 'fa-solid fa-user-group fa-fw',
                'icon_color'                => '#3d85c6',
                'jenis'                     => 'Menu',
                'parent_name'               => '',
                'urut'                      => 0,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 8,
                'judul'                     => 'Grup User',
                'icon'                      => 'fa-solid fa-users-gear fa-fw',
                'icon_color'                => '#b6d7a8',
                'jenis'                     => 'Menu',
                'parent_name'               => 'manajemen_user',
                'urut'                      => 0,
                'url'                       => 'user',
                'is_page'                   => 1,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 9,
                'judul'                     => 'Lihat Grup User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'grup_user',
                'urut'                      => 0,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 10,
                'judul'                     => 'Tambah Grup User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'grup_user',
                'urut'                      => 1,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 11,
                'judul'                     => 'Edit Grup User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'grup_user',
                'urut'                      => 2,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 12,
                'judul'                     => 'Hapus Grup User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'grup_user',
                'urut'                      => 3,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 13,
                'judul'                     => 'Daftar User',
                'icon'                      => 'fa-solid fa-user-large fa-fw',
                'icon_color'                => '#ffe599',
                'jenis'                     => 'Menu',
                'parent_name'               => 'manajemen_user',
                'urut'                      => 1,
                'url'                       => 'user',
                'is_page'                   => 1,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 14,
                'judul'                     => 'Lihat Daftar User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'daftar_user',
                'urut'                      => 0,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 15,
                'judul'                     => 'Tambah Daftar User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'daftar_user',
                'urut'                      => 1,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 16,
                'judul'                     => 'Edit Daftar User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'daftar_user',
                'urut'                      => 2,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
            [
                'auth_permissions_id'       => 17,
                'judul'                     => 'Hapus Daftar User',
                'icon'                      => '',
                'icon_color'                => '',
                'jenis'                     => 'Action',
                'parent_name'               => 'daftar_user',
                'urut'                      => 3,
                'url'                       => '',
                'is_page'                   => 0,
                'status'                    => 'active',
            ],
        ];

        $this->db->table('sistem_otoritas')->insertBatch($data);
    }
}
